# Generated by Django 3.2.25 on 2024-09-17 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starrating',
            name='star',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
