# Generated by Django 3.2.25 on 2024-09-17 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_starrating_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reply_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='api.message'),
        ),
    ]
