# Generated by Django 5.1.1 on 2024-09-24 14:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='max_capacity',
            new_name='capacity',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='max_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='min_capacity',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='min_price',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='room_availability',
        ),
        migrations.AddField(
            model_name='destination',
            name='city',
            field=models.CharField(default='dehli', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
