# Generated by Django 5.1.1 on 2024-09-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_max_capacity_destination_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='facilities',
            field=models.ManyToManyField(related_name='destination', to='api.facility'),
        ),
    ]
